<a href="https://colab.research.google.com/github/ShaluPriya-R01/visual-aids-2/blob/main/linearregression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#importing nescessary libraries
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder


importing dataset

In [ ]:
df = pd.read_csv("/content/iris.csv")

In [ ]:
df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

Transforming string values using label encoder

In [ ]:
le=LabelEncoder()
le.fit_transform(df["species"])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
x =df.drop(columns= "species",axis=1)

In [ ]:
y=le.fit_transform(df["species"])

Split dataset into train data and test data

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.5, random_state=0)

In [ ]:
x_train

sepal_length  sepal_width  petal_length  petal_width
3             4.6          3.1           1.5          0.2
149           5.9          3.0           5.1          1.8
98            5.1          2.5           3.0          1.1
6             4.6          3.4           1.4          0.3
68            6.2          2.2           4.5          1.5
..            ...          ...           ...          ...
9             4.9          3.1           1.5          0.1
103           6.3          2.9           5.6          1.8
67            5.8          2.7           4.1          1.0
117           7.7          3.8           6.7          2.2
47            4.6          3.2           1.4          0.2

[75 rows x 4 columns]

In [ ]:
x_test

sepal_length  sepal_width  petal_length  petal_width
114           5.8          2.8           5.1          2.4
62            6.0          2.2           4.0          1.0
33            5.5          4.2           1.4          0.2
107           7.3          2.9           6.3          1.8
7             5.0          3.4           1.5          0.2
..            ...          ...           ...          ...
111           6.4          2.7           5.3          1.9
95            5.7          3.0           4.2          1.2
20            5.4          3.4           1.7          0.2
15            5.7          4.4           1.5          0.4
52            6.9          3.1           4.9          1.5

[75 rows x 4 columns]

In [ ]:

y_train

array([0, 2, 1, 0, 1, 2, 1, 0, 2, 2, 2, 2, 0, 0, 2, 2, 0, 2, 0, 2, 2, 0,
       0, 2, 0, 0, 0, 1, 2, 2, 0, 0, 0, 1, 1, 0, 0, 1, 0, 2, 1, 2, 1, 0,
       2, 0, 2, 0, 0, 2, 0, 2, 1, 1, 1, 2, 2, 1, 1, 0, 1, 2, 2, 0, 1, 1,
       1, 1, 0, 0, 0, 2, 1, 2, 0])

In [ ]:
y_test

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0, 2, 1, 0, 2, 2, 1, 0, 1, 1, 1, 2, 0, 2, 0,
       0, 1, 2, 2, 2, 2, 1, 2, 1, 1, 2, 2, 2, 2, 1, 2, 1, 0, 2, 1, 1, 1,
       1, 2, 0, 0, 2, 1, 0, 0, 1])

Create variable model as an instance of linearregression

In [ ]:

model = LinearRegression()

Fit the train and test data into the model

In [ ]:
model.fit(x_train,y_train)

LinearRegression()

Predict the dependent variable value based on training data of independent data

In [ ]:
y_trainpredict=model.predict(x_train)

In [ ]:
y_trainpredict

array([ 2.93133174e-02,  1.68473781e+00,  8.25870048e-01,  7.71920113e-02,
        1.26649091e+00,  2.18695444e+00,  1.18833085e+00, -8.91209036e-02,
        1.88740598e+00,  1.98980319e+00,  2.00688569e+00,  1.90090772e+00,
        2.17020295e-02,  4.31465552e-02,  1.72112834e+00,  1.91142104e+00,
        2.61492536e-03,  2.02627451e+00, -4.70586331e-02,  1.77315372e+00,
        1.79168049e+00,  1.22341965e-02, -2.74089719e-02,  1.56205097e+00,
        8.91090512e-03,  7.49409475e-04,  1.22979721e-01,  1.13105497e+00,
        2.05703881e+00,  1.99689068e+00, -4.79560654e-02, -7.19677529e-02,
       -6.85031588e-02,  1.26123483e+00,  1.17012883e+00, -1.02809460e-01,
        1.89806430e-01,  1.11091341e+00,  4.18368394e-02,  2.15149672e+00,
        8.71516455e-01,  1.88911784e+00,  1.16106652e+00, -5.89579175e-02,
        1.59128674e+00, -1.75307912e-01,  1.93994968e+00,  5.23535428e-02,
        4.64664681e-02,  1.77020406e+00, -4.46361525e-02,  2.12076769e+00,
        1.15637300e+00,  

Predict the dependent variable value based on testing independent data

In [ ]:


y_predicttest=model.predict(x_test)

In [ ]:
y_predicttest

array([ 2.02925954,  0.88068817, -0.06697811,  1.7863151 , -0.0126783 ,
        2.2767541 , -0.00249985,  1.29657986,  1.23389647,  1.07093874,
        1.53576824,  1.29430544,  1.19757997,  1.28274662,  1.3170563 ,
       -0.07196775,  1.33629706,  1.19627701,  0.02461304,  0.01811789,
        1.77897015,  1.40125825,  0.12179293,  0.02122247,  1.55019255,
       -0.073052  ,  0.21408234,  1.14052281,  0.85096936,  0.1272711 ,
        1.72131853,  1.43086765, -0.03654531,  1.60269749,  1.95777469,
        1.22909016,  0.01595626,  1.53897199,  1.27819778,  1.04700108,
        1.82695825, -0.0321799 ,  1.82676806,  0.24674743, -0.05466992,
        0.8861731 ,  1.70077144,  2.13888893,  1.42717759,  1.72109644,
        0.98778566,  1.96474263,  1.42415042,  0.97063251,  1.55586091,
        1.44343331,  1.58991313,  1.62745855,  1.20104119,  1.73585901,
        1.421876  ,  0.02591937,  1.7391823 ,  1.19165076,  1.04584281,
        1.14253976,  1.29658324,  1.73970061, -0.03986522, -0.09

MSE of Y test

In [ ]:
mean_squared_error(y_test,y_predicttest,squared=False)

0.2528859553616415

In [ ]:
MSE of Y train

In [ ]:
mean_squared_error(y_train,y_trainpredict,squared=False)

0.17683089296942295

RMSE of Y test

In [ ]:
mean_squared_error(y_test,y_predicttest,squared=True)

0.06395130641917014

RMSE of Y train

In [ ]:
mean_squared_error(y_train,y_trainpredict,squared=True)

0.031269164708363516